tags:
  - Users
description: |
  Allows a user to get their own settings.
  Requires a valid JWT token for authentication.
security:
  - JWT: []
responses:
  200:
    description: User settings retrieved successfully.
    schema:
      type: object
      properties:
        id:
          type: integer
          example: 1
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Doe
        email:
          type: string
          example:
        phone_number:
          type: string
          example:
        bio:
          type: string
          example:
        profile_picture:
          type: string
          example:
        theme:
          type: string
          example:
  401:
    description: Unauthorized.  Missing or invalid JWT token.
    schema:
      type: object
      properties:
        message:
          type: string
          example: Missing Authorization Header
  500:
    description: Internal server error.
    schema:
      type: object
      properties:
        message:
          type: string
          example: "Failed to retrieve user settings"