name: Label PRs

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get list of modified files
        id: files
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --name-only origin/${{ github.event.pull_request.base.ref }} > files.txt
          cat files.txt

      - name: Set labels
        id: set-labels
        run: |
          labels=""
          if grep -q '^backend/' files.txt; then
            labels="${labels}backend,"
          fi
          if grep -q '^frontend/' files.txt; then
            labels="${labels}frontend,"
          fi
          if grep -q '^.github/workflows/' files.txt; then
            labels="${labels}workflow,"
          fi
          echo "::set-output name=labels::${labels%,}"

      - name: Add labels to PR
        if: steps.set-labels.outputs.labels != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ${{ steps.set-labels.outputs.labels }}
          github_token: ${{ secrets.GITHUB_TOKEN }}