name: Run backend tests on Docker compose

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run docker-compose
        run: |
          docker-compose --profile backend up -d

      - name: Execute Makefile target
        run: |
          docker-compose exec -T worker poetry run pytest

      - name: Tear down Docker Compose
        if: always()
        run: |
          docker-compose down
